Repository t10d/cra-template-kingdom, pull requests merged in 2021-04, with the labels that each got.

#9 Project Structure and Routing
  template.json
  template/src/App.css
  template/src/App.test.tsx
  template/src/App.tsx
  template/src/context/AuthContext.tsx
  template/src/index.css
  template/src/index.tsx
  template/src/pages/Login/index.tsx
  template/src/pages/NotFoundPage/index.tsx
  template/src/pages/User/index.tsx
  template/src/pages/index/AuthApp.tsx
  template/src/pages/index/UnAuthApp.tsx
  template/src/routes/authRoutes.ts
  template/src/utils/cache.ts
Labels: enhancement, help wanted

#11 Removing in-memory cache
  template/src/context/AuthContext.tsx
  template/src/utils/cache.ts
Labels: help wanted

#18 Setup and initial tests
  .gitignore
  template.json
  template/src/__tests__/App.test.tsx
  template/src/pages/Login/index.tsx
  template/src/pages/User/index.tsx
  template/src/pages/index/__tests__/AuthApp.test.tsx
  template/src/pages/index/__tests__/unAuthApp.test.tsx
  template/src/utils/test.tsx
Labels: documentation

#22 Feature/API integration (MirageJS+Axios)
  template.json
  template/.env.development
  template/src/index.tsx
  template/src/server.js
  template/src/services/api.ts
Labels: enhancement

#23 Issue 21 storybook
  .gitignore
  template.json
  template/.storybook/main.js
  template/.storybook/preview.js
  template/gitignore
Labels: enhancement
